version: '3'
networks:
  sif.docker-internal:
    external:
      name: sif.docker-internal
services:
  flex-oidc-provider-gui:
    container_name: flex-oidc-provider-gui
    networks:
      sif.docker-internal:
        aliases:
          - flex-oidc-provider-gui.sif.docker-internal
    image: "docker.pkg.github.com/navikt/flex-docker-compose/flex-oidc-provider-gui:latest"
    ports:
      - "5000:5000"
    depends_on:
      - oidc-provider
    environment:
      REDIRECT_URL: "http://localhost:8080"
      AUTO_REDIRECT_TO_FRONTEND: "true"

  oidc-provider:
    container_name: oidc-provider
    networks:
      sif.docker-internal:
        aliases:
          - oidc-provider.sif.docker-internal
    image: "docker.pkg.github.com/navikt/flex-docker-compose/flex-stub-oidc-provider:latest"
    ports:
      - "9000:9000"
    environment:
      PORT: "9000"
      CALLBACK_URL: "http://localhost:5000/callback"
      ISSUER: "https://localhost:9000"

  wiremock:
    container_name: wiremock
    networks:
      sif.docker-internal:
        aliases:
          - wiremock.sif.docker-internal
    image: "rodolpheche/wiremock"
    volumes:
    - "./wiremock/stubs:/home/wiremock"
    ports:
      - "8000:8080"

  db:
    container_name: db
    image: 'postgres'
    networks:
      sif.docker-internal:
        aliases:
          - db.sif.docker-internal
    restart: on-failure
    hostname: localhost
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password

  sif-innsyn-api:
    container_name: sif-innsyn-api
    image: 'sif-innsyn-api-local:latest'
    networks:
      sif.docker-internal:
        aliases:
          - sif-innsyn-api.sif.docker-internal
    restart: on-failure
    env_file:
      - sif-innsyn-api.env
    ports:
      - "8080:8080"
    hostname: localhost
    depends_on:
      - db
