no.nav:
  apigw:
    apikey: ${APIGW_API_KEY} # kubectl secret
    sts-apikey: ${STS_APIKEY} # kubectl secret
  gateways:
    k9-selvbetjening-oppslag: ${K9_OPPSLAG_REGISTER_URL}
    sts:
      url: ${SECURITY_TOKEN_SERVICE_REST_URL}
      username: ${STS_USERNAME}
      password: ${STS_PASSWORD}
  security:
    cors:
      allowed-origins: https://sif-innsyn.dev-gcp.nais.io,https://sif-innsyn.dev.nav.no,https://www-q0.nav.no
    jwt:
      issuer:
        selvbetjening:
           discoveryUrl: https://login.microsoftonline.com/NAVtestB2C.onmicrosoft.com/v2.0/.well-known/openid-configuration?p=B2C_1A_idporten_ver1
           cookie_name: selvbetjening-idtoken

management:
   endpoints:
      web:
         exposure:
            include: health, prometheus
   endpoint:
      health:
         show-details: always
spring:
  rest:
    retry:
      multiplier: 2
      initialDelay: 1000
      maxDelay: 4000
      maxAttempts: 3
  application:
    name: sif-innsyn-api
  datasource:
    hikari:
      connection-test-query: SELECT 1
      maximum-pool-size: 2
    url: jdbc:postgresql://${NAIS_DATABASE_SIF_INNSYN_API_SIF_INNSYN_DB_HOST}:${NAIS_DATABASE_SIF_INNSYN_API_SIF_INNSYN_DB_PORT}/${NAIS_DATABASE_SIF_INNSYN_API_SIF_INNSYN_DB_DATABASE}
    username: ${NAIS_DATABASE_SIF_INNSYN_API_SIF_INNSYN_DB_USERNAME}
    password: ${NAIS_DATABASE_SIF_INNSYN_API_SIF_INNSYN_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  flyway:
    baselineOnMigrate: true
    enabled: true
    clean-on-validation-error: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
  kafka:
    properties:
      schema:
        registry:
          url:   https://kafka-schema-registry.nais.adeo.no
      security:
        protocol:
      sasl:
        mechanism: PLAIN
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username=${sts.username} password=${sts.password};
    consumer:
      enable-auto-commit: false
      bootstrap-servers:
      group-id: group_id
      auto-offset-reset: earliest
      retry-interval: 60_000 # Egendefinert property
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      ssl:
        trust-store-location: file:${javax.net.ssl.trustStore}
        trust-store-password: ${javax.net.ssl.trustStorePassword}
  mvc:
    log-request-details: true
