management:
   endpoints:
      web:
         exposure:
            include: '*'
   endpoint:
      health:
         show-details: always

server:
   port: # Settes av miljøvariabel.
spring:
   cloud:
      vault:
         database:
            role: # Settes av miljøvariabel.
   output:
    ansi:
      enabled: always
   application:
      name: sif-innsyn-api
      admin:
         enabled: true
   datasource:
      url: # Settes av miljøvariabel.
      password: # Settes av miljøvariabel.
      username: # Settes av miljøvariabel.
   jpa:
      show-sql: true
      properties:
         hibernate: format_sql=true
      hibernate:
         ddl-auto: create-drop
   flyway:
      baselineOnMigrate: true
      enabled: true
   http:
      log-request-details: true
