management:
  endpoint:
    health:
      show-details: always

spring:
  flyway:
    url: jdbc:postgresql://${NAIS_DATABASE_SIF_INNSYN_API_SIF_INNSYN_DB_HOST}:${NAIS_DATABASE_SIF_INNSYN_API_SIF_INNSYN_DB_PORT}/${NAIS_DATABASE_SIF_INNSYN_API_SIF_INNSYN_DB_DATABASE}

  mvc:
    log-request-details: true

  kafka:
    properties:
      security:
        protocol: # Settes i nais/<cluster>.json
      sasl:
        mechanism: PLAIN
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username="${sts.username}" password="${sts.password}";

    producer:
      ssl:
        trust-store-location: file:${javax.net.ssl.trustStore}
        trust-store-password: ${javax.net.ssl.trustStorePassword}

    consumer:
      ssl:
        trust-store-location: file:${javax.net.ssl.trustStore}
        trust-store-password: ${javax.net.ssl.trustStorePassword}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

no.nav.security.jwt.issuer:
  loginservice:
    discoveryUrl: ${LOGINSERVICE_IDPORTEN_DISCOVERY_URL} # settes av configmap: loginservice-idporten i naiserator.yml
    accepted_audience: ${LOGINSERVICE_IDPORTEN_AUDIENCE} # settes av configmap: loginservice-idporten i naiserator.yml
